# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

# name is used for the variable $(build.buildNumber)
name: 1.0.$(Date:yyMM).$(build.buildId)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: InstallDependencies
    steps:

    - task: UseDotNet@2
      displayName: 'Use .NET Core 3.1.11 sdk'
      inputs:
        packageType: sdk
        version: 3.1.405
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: './Anlab.MVC'

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

  - job: BuildAndTest
    dependsOn: InstallDependencies
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build Anlab.Mvc'
      inputs:
        command: 'build'
        projects: './Anlab.Mvc/AnlabMvc.csproj'
        arguments: '--configuration $(BuildConfiguration) /property:Version=$(build.buildNumber)'

    - task: DotNetCoreCLI@2
      displayName: 'Run Server Tests'
      inputs:
        command: 'test'

    - task: Npm@1
      displayName: 'npm test'
      inputs:
        command: 'custom'
        workingDir: 'Anlab.MVC'
        customCommand: 'test'

- stage: Deploy
  jobs:
  - job: PublishArtifacts
    steps:

    - task: DotNetCoreCLI@2
      displayName: 'Publish Anlab.Mvc'
      inputs:
        command: 'publish'
        publishWebProjects: true
        zipAfterPublish: true
        modifyOutputPath: false
        projects: './Anlab.Mvc/AnlabMvc.csproj'
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Anlab.Jobs.MoneyMovement'
      inputs:
        command: 'publish'
        publishWebProjects: false
        zipAfterPublish: true
        modifyOutputPath: false
        projects: './Anlab.Jobs.MoneyMovement/Anlab.Jobs.MoneyMovement.csproj'
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Anlab.Jobs.SendMail'
      inputs:
        command: 'publish'
        publishWebProjects: false
        zipAfterPublish: true
        modifyOutputPath: false
        projects: './Anlab.Jobs.SendMail/Anlab.Jobs.SendMail.csproj'
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
